language: python
python:
  - '2.7'
branches:
  only: develop
install:
  - pip install awscli
  - pip install aws-sam-cli
script:
  - aws sts get-caller-identity
  - export AWS_DEFAULT_REGION=us-west-2
  - export BUILD_BUCKET=sam-build-ci
  - export SAM_STACK_NAME=polly-api-pollydev
  - cd api
  - sam validate
  #- sam --region us-west-2 validate
  - sam package --template-file template.yaml --s3-bucket ${BUILD_BUCKET} --output-template-file interim-template.yaml
  - sam deploy  --template-file interim-template.yaml --stack-name ${SAM_STACK_NAME} --capabilities CAPABILITY_IAM
notifications:
  email:
    on_failure: always
