# uses aws/codebuild/nodejs:8.11.0
# AWS_REGION is auto populated from CodeBuild
#
version: 0.2

phases:

  install:
    commands:
      - npm install -g serverless
  build:
    commands:
  post_build:
    commands:
      - cd api
      - serverless deploy --stage dev --region $AWS_REGION
      - serverless info --region $AWS_REGION

artifacts:
  files:
    - api/serverless.yml
  base-directory: build
